name: vsdroid
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  android_intent_plus: ^6.0.0
  bloc: ^9.0.0
  # code_forge:
  #   git:
  #     url: https://github.com/heckmon/code_forge
  #     ref: 35f1cee396c91ebc9d44b5da39c29b675578b5df
  code_forge:
    path: /home/athul/Projects/code_forge
  file_icon: ^1.0.0
  file_picker: ^10.2.0
  filesystem_picker: ^4.1.0
  flutter:
    sdk: flutter
  flutter_archive: ^6.0.3
  flutter_bloc: ^9.1.1
  flutter_downloader: ^1.12.0
  flutter_inappwebview: ^6.1.5
  flutter_json: ^0.0.5
  flutter_pty: ^0.4.1
  flutter_svg: ^2.2.0
  flutter_switch: ^0.3.2
  font_awesome_flutter: ^10.10.0
  http: ^1.2.2
  markdown_widget: ^2.3.2+8
  path: ^1.9.0
  percent_indicator: ^4.2.5
  permission_handler: ^12.0.1
  re_highlight: ^0.0.3
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  xterm: ^4.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/material_icons/
    - assets/webview/
    - assets/fonts/
  fonts:
    - family: firaCode
      fonts:
        - asset: assets/fonts/FiraCode-Medium.ttf
    - family: cascadia
      fonts:
        - asset: assets/fonts/CascadiaCodePL-Regular.ttf
    - family: hack
      fonts:
        - asset: assets/fonts/Hack-Regular.ttf
    - family: dejaVuSansMono
      fonts:
        - asset: assets/fonts/DejaVuSansMono.ttf
    - family: inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
    - family: jetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Medium.ttf
    - family: proggy
      fonts:
        - asset: assets/fonts/ProggyVector-Regular.ttf
    - family: sourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-Medium.ttf
    
    #LSP Icons
    - family: Method
      fonts:
        - asset: assets/icons/method.ttf
    - family: Variable
      fonts:
        - asset: assets/icons/variable.ttf
    - family: Class
      fonts:
        - asset: assets/icons/class.ttf
    - family: Enum
      fonts:
        - asset: assets/icons/enum.ttf
    - family: KeyWord
      fonts:
        - asset: assets/icons/keyword.ttf
    - family: Reference
      fonts:
        - asset: assets/icons/reference.ttf
    - family: Constant
      fonts:
        - asset: assets/icons/constant.ttf
    - family: Struct
      fonts:
        - asset: assets/icons/struct.ttf
    - family: Event
      fonts:
        - asset: assets/icons/event.ttf
    - family: Operator
      fonts:
        - asset: assets/icons/operator.ttf
    - family: Parameter
      fonts:
        - asset: assets/icons/parameter.ttf
    - family: Snippet
      fonts:
        - asset: assets/icons/snippet.ttf
    - family: Interface
      fonts:
        - asset: assets/icons/interface.ttf
    - family: Field
      fonts:
        - asset: assets/icons/field.ttf
